$(document).ready(function () {
    $('.menu').on('click', function () {
        $(this).toggleClass('active');
        $('.menu__body').toggleClass('active');
    });

    $('.tel').tipso({
        speed: 400,
        background: '#5DC145',
        titleBackground: '#5DC145',
        color: '#ffffff',
        titleColor: '#ffffff',
        titleContent: 'Зателефонувати',
        showArrow: true,
        position: 'top',
        width: 200,
        maxWidth: '',
        delay: 0,
        hideDelay: 0,
        animationIn: '',
        animationOut: '',
        offsetX: 0,
        offsetY: -30,
        tooltipHover: false,
        content: 'Phone me',
        ajaxContentUrl: null,
        contentElementId: null,
        useTitle: false,
        templateEngineFunc: null,
        onBeforeShow: null,
        onShow: null,
        onHide: null,
    });

    $('.mail').tipso({
        speed: 400,
        background: '#FC2C38',
        titleBackground: '#FC2C38',
        color: '#ffffff',
        titleColor: '#ffffff',
        titleContent: 'Написати листа',
        showArrow: true,
        position: 'top',
        width: 200,
        maxWidth: '',
        delay: 0,
        hideDelay: 0,
        animationIn: '',
        animationOut: '',
        offsetX: 0,
        offsetY: -30,
        tooltipHover: false,
        content: 'Mail me',
        ajaxContentUrl: null,
        contentElementId: null,
        useTitle: false,
        templateEngineFunc: null,
        onBeforeShow: null,
        onShow: null,
        onHide: null,
    });

    $('.telegram').tipso({
        speed: 400,
        background: '#239edf',
        titleBackground: '#239edf',
        color: '#ffffff',
        titleColor: '#ffffff',
        titleContent: 'Написати в телеграм',
        showArrow: true,
        position: 'top',
        width: 200,
        maxWidth: '',
        delay: 0,
        hideDelay: 0,
        animationIn: '',
        animationOut: '',
        offsetX: 0,
        offsetY: -30,
        tooltipHover: false,
        content: 'Telegram me',
        ajaxContentUrl: null,
        contentElementId: null,
        useTitle: false,
        templateEngineFunc: null,
        onBeforeShow: null,
        onShow: null,
        onHide: null,
    });

    $('.pinterest').tipso({
        speed: 400,
        background: '#e60023',
        titleBackground: '#e60023',
        color: '#ffffff',
        titleColor: '#ffffff',
        titleContent: 'Мій пін',
        showArrow: true,
        position: 'top',
        width: 200,
        maxWidth: '',
        delay: 0,
        hideDelay: 0,
        animationIn: '',
        animationOut: '',
        offsetX: 0,
        offsetY: -30,
        tooltipHover: false,
        content: 'My pinterest',
        ajaxContentUrl: null,
        contentElementId: null,
        useTitle: false,
        templateEngineFunc: null,
        onBeforeShow: null,
        onShow: null,
        onHide: null,
    });
    $('.facebook').tipso({
        speed: 400,
        background: '#1877f2',
        titleBackground: '#1877f2',
        color: '#ffffff',
        titleColor: '#ffffff',
        titleContent: 'Мій фейсбук',
        showArrow: true,
        position: 'top',
        width: 200,
        maxWidth: '',
        delay: 0,
        hideDelay: 0,
        animationIn: '',
        animationOut: '',
        offsetX: 0,
        offsetY: -30,
        tooltipHover: false,
        content: 'My facebook',
        ajaxContentUrl: null,
        contentElementId: null,
        useTitle: false,
        templateEngineFunc: null,
        onBeforeShow: null,
        onShow: null,
        onHide: null,
    });
    $('.behance').tipso({
        speed: 400,
        background: '#0b65f9',
        titleBackground: '#0b65f9',
        color: '#ffffff',
        titleColor: '#ffffff',
        titleContent: 'Мій беханс',
        showArrow: true,
        position: 'top',
        width: 200,
        maxWidth: '',
        delay: 0,
        hideDelay: 0,
        animationIn: '',
        animationOut: '',
        offsetX: 0,
        offsetY: -30,
        tooltipHover: false,
        content: 'My behance',
        ajaxContentUrl: null,
        contentElementId: null,
        useTitle: false,
        templateEngineFunc: null,
        onBeforeShow: null,
        onShow: null,
        onHide: null,
    });
    $('.youtube').tipso({
        speed: 400,
        background: '#ff0000',
        titleBackground: '#ff0000',
        color: '#ffffff',
        titleColor: '#ffffff',
        titleContent: 'Мій ютуб',
        showArrow: true,
        position: 'top',
        width: 200,
        maxWidth: '',
        delay: 0,
        hideDelay: 0,
        animationIn: '',
        animationOut: '',
        offsetX: 0,
        offsetY: -30,
        tooltipHover: false,
        content: 'My youtube',
        ajaxContentUrl: null,
        contentElementId: null,
        useTitle: false,
        templateEngineFunc: null,
        onBeforeShow: null,
        onShow: null,
        onHide: null,
    });
    $('.instagram').tipso({
        speed: 400,
        background: '#b43ba4',
        titleBackground: '#b43ba4',
        color: '#ffffff',
        titleColor: '#ffffff',
        titleContent: 'Мій інстаграм',
        showArrow: true,
        position: 'top',
        width: 200,
        maxWidth: '',
        delay: 0,
        hideDelay: 0,
        animationIn: '',
        animationOut: '',
        offsetX: 0,
        offsetY: -30,
        tooltipHover: false,
        content: 'My instagram',
        ajaxContentUrl: null,
        contentElementId: null,
        useTitle: false,
        templateEngineFunc: null,
        onBeforeShow: null,
        onShow: null,
        onHide: null,
    });
});

$('.instagram').tipso({
    speed: 400,
    background: '#1877f2',
    titleBackground: '#1877f2',
    color: '#ffffff',
    titleColor: '#ffffff',
    titleContent: 'Мій інстаграм',
    showArrow: true,
    position: 'top',
    width: 200,
    maxWidth: '',
    delay: 0,
    hideDelay: 0,
    animationIn: '',
    animationOut: '',
    offsetX: 0,
    offsetY: -30,
    tooltipHover: false,
    content: 'My instagram',
    ajaxContentUrl: null,
    contentElementId: null,
    useTitle: false,
    templateEngineFunc: null,
    onBeforeShow: null,
    onShow: null,
    onHide: null,
});

document.querySelectorAll('.accordeon__triger').forEach((item) => {
    item.addEventListener('click', () => {
        item.parentNode.classList.toggle('accordeon__item--active');
    });
});

var container1 = document.querySelector('[data-ref="container-1"]');
var container2 = document.querySelector('[data-ref="container-2"]');

var config = {
    controls: {
        scope: 'local',
    },
};

var mixer1 = mixitup(container1, config);
var mixer2 = mixitup(container2, config);
